### ISSUE TITLE
S3 local

### ISSUE THREAD

**Issue by piotr-kalanski** [piotr-kalanski/big-data-dev-environment-docker#1]
https://hub.docker.com/r/lphoward/fake-s3/
https://github.com/jubos/fake-s3

**Comment by piotr-kalanski** [comment]
```  
# This configuration allows you to start local S3 based on fakes3 (https://github.com/jubos/fake-s3)
  s3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569
```
